name: "Build and deploy Github pages"

on:
  push:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: "Install Python dependencies"
        run: |
          pip3 install setuptools
          pip3 install nox

      - name: "Build Sphinx Doc"
        run: |
          nox --session gendoc

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/html
